// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/client/runtime";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  client: {
    // URL do Neon PostgreSQL
    adapter: 'postgresql',
    url: process.env.D// pegue do .env
  },
});
